version: "3.9"

services:
  consumer:
    image: rubru/jellytoring-model
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - ./consumer-model/testdir:/testdir
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    - "15692:15692"
  prometheus:
    image: rubru/jellytoring-prometheus
    restart: always
    ports:
      - "9090:9090"
  grafana:
    image: rubru/jellytoring-grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
