CREATE DATABASE IF NOT EXISTS jellytoring;

use jellytoring;

CREATE TABLE IF NOT EXISTS `interests`(
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` varchar(20) NOT NULL,
    PRIMARY KEY (`id`)
);

INSERT INTO `interests` (`name`) VALUES('Scientific'), ('Divulgation'), ('Educational'), ('Other');

CREATE TABLE IF NOT EXISTS `countries` (
	`id` int(11) UNSIGNED NOT NULL,
	`phone_code` int(5) NOT NULL,
	`country_code` char(2) NOT NULL,
	`country_code_alpha_3` char(3) DEFAULT NULL,
	`country_name` varchar(80) NOT NULL,
	`continent_code` varchar(2) DEFAULT NULL,
	PRIMARY KEY (`country_code`)
);

-- https://www.html-code-generator.com/mysql/country-name-table

INSERT INTO `countries` (`id`, `phone_code`, `country_code`, `country_code_alpha_3`, `country_name`, `continent_code`) VALUES
    (1,93,'AF','AFG','Afghanistan','AS'),
    (2,358,'AX','ALA','Aland Islands','EU'),
    (3,355,'AL','ALB','Albania','EU'),
    (4,213,'DZ','DZA','Algeria','AF'),
    (5,1684,'AS','ASM','American Samoa','OC'),
    (6,376,'AD','AND','Andorra','EU'),
    (7,244,'AO','AGO','Angola','AF'),
    (8,1264,'AI','AIA','Anguilla','NA'),
    (9,672,'AQ','ATA','Antarctica','AN'),
    (10,1268,'AG','ATG','Antigua and Barbuda','NA'),
    (11,54,'AR','ARG','Argentina','SA'),
    (12,374,'AM','ARM','Armenia','AS'),
    (13,297,'AW','ABW','Aruba','NA'),
    (14,61,'AU','AUS','Australia','OC'),
    (15,43,'AT','AUT','Austria','EU'),
    (16,994,'AZ','AZE','Azerbaijan','AS'),
    (17,1242,'BS','BHS','Bahamas','NA'),
    (18,973,'BH','BHR','Bahrain','AS'),
    (19,880,'BD','BGD','Bangladesh','AS'),
    (20,1246,'BB','BRB','Barbados','NA'),
    (21,375,'BY','BLR','Belarus','EU'),
    (22,32,'BE','BEL','Belgium','EU'),
    (23,501,'BZ','BLZ','Belize','NA'),
    (24,229,'BJ','BEN','Benin','AF'),
    (25,1441,'BM','BMU','Bermuda','NA'),
    (26,975,'BT','BTN','Bhutan','AS'),
    (27,591,'BO','BOL','Bolivia','SA'),
    (28,599,'BQ','BES','Bonaire, Sint Eustatius and Saba','NA'),
    (29,387,'BA','BIH','Bosnia and Herzegovina','EU'),
    (30,267,'BW','BWA','Botswana','AF'),
    (31,55,'BV','BVT','Bouvet Island','AN'),
    (32,55,'BR','BRA','Brazil','SA'),
    (33,246,'IO','IOT','British Indian Ocean Territory','AS'),
    (34,673,'BN','BRN','Brunei Darussalam','AS'),
    (35,359,'BG','BGR','Bulgaria','EU'),
    (36,226,'BF','BFA','Burkina Faso','AF'),
    (37,257,'BI','BDI','Burundi','AF'),
    (38,855,'KH','KHM','Cambodia','AS'),
    (39,237,'CM','CMR','Cameroon','AF'),
    (40,1,'CA','CAN','Canada','NA'),
    (41,238,'CV','CPV','Cape Verde','AF'),
    (42,1345,'KY','CYM','Cayman Islands','NA'),
    (43,236,'CF','CAF','Central African Republic','AF'),
    (44,235,'TD','TCD','Chad','AF'),
    (45,56,'CL','CHL','Chile','SA'),
    (46,86,'CN','CHN','China','AS'),
    (47,61,'CX','CXR','Christmas Island','AS'),
    (48,672,'CC','CCK','Cocos (Keeling) Islands','AS'),
    (49,57,'CO','COL','Colombia','SA'),
    (50,269,'KM','COM','Comoros','AF'),
    (51,242,'CG','COG','Congo','AF'),
    (52,242,'CD','COD','Congo, Democratic Republic of the Congo','AF'),
    (53,682,'CK','COK','Cook Islands','OC'),
    (54,506,'CR','CRI','Costa Rica','NA'),
    (55,225,'CI','CIV','Cote DIvoire','AF'),
    (56,385,'HR','HRV','Croatia','EU'),
    (57,53,'CU','CUB','Cuba','NA'),
    (58,599,'CW','CUW','Curacao','NA'),
    (59,357,'CY','CYP','Cyprus','AS'),
    (60,420,'CZ','CZE','Czech Republic','EU'),
    (61,45,'DK','DNK','Denmark','EU'),
    (62,253,'DJ','DJI','Djibouti','AF'),
    (63,1767,'DM','DMA','Dominica','NA'),
    (64,1809,'DO','DOM','Dominican Republic','NA'),
    (65,593,'EC','ECU','Ecuador','SA'),
    (66,20,'EG','EGY','Egypt','AF'),
    (67,503,'SV','SLV','El Salvador','NA'),
    (68,240,'GQ','GNQ','Equatorial Guinea','AF'),
    (69,291,'ER','ERI','Eritrea','AF'),
    (70,372,'EE','EST','Estonia','EU'),
    (71,251,'ET','ETH','Ethiopia','AF'),
    (72,500,'FK','FLK','Falkland Islands (Malvinas)','SA'),
    (73,298,'FO','FRO','Faroe Islands','EU'),
    (74,679,'FJ','FJI','Fiji','OC'),
    (75,358,'FI','FIN','Finland','EU'),
    (76,33,'FR','FRA','France','EU'),
    (77,594,'GF','GUF','French Guiana','SA'),
    (78,689,'PF','PYF','French Polynesia','OC'),
    (79,262,'TF','ATF','French Southern Territories','AN'),
    (80,241,'GA','GAB','Gabon','AF'),
    (81,220,'GM','GMB','Gambia','AF'),
    (82,995,'GE','GEO','Georgia','AS'),
    (83,49,'DE','DEU','Germany','EU'),
    (84,233,'GH','GHA','Ghana','AF'),
    (85,350,'GI','GIB','Gibraltar','EU'),
    (86,30,'GR','GRC','Greece','EU'),
    (87,299,'GL','GRL','Greenland','NA'),
    (88,1473,'GD','GRD','Grenada','NA'),
    (89,590,'GP','GLP','Guadeloupe','NA'),
    (90,1671,'GU','GUM','Guam','OC'),
    (91,502,'GT','GTM','Guatemala','NA'),
    (92,44,'GG','GGY','Guernsey','EU'),
    (93,224,'GN','GIN','Guinea','AF'),
    (94,245,'GW','GNB','Guinea-Bissau','AF'),
    (95,592,'GY','GUY','Guyana','SA'),
    (96,509,'HT','HTI','Haiti','NA'),
    (97,0,'HM','HMD','Heard Island and Mcdonald Islands','AN'),
    (98,39,'VA','VAT','Holy See (Vatican City State)','EU'),
    (99,504,'HN','HND','Honduras','NA'),
    (100,852,'HK','HKG','Hong Kong','AS'),
    (101,36,'HU','HUN','Hungary','EU'),
    (102,354,'IS','ISL','Iceland','EU'),
    (103,91,'IN','IND','India','AS'),
    (104,62,'ID','IDN','Indonesia','AS'),
    (105,98,'IR','IRN','Iran, Islamic Republic of','AS'),
    (106,964,'IQ','IRQ','Iraq','AS'),
    (107,353,'IE','IRL','Ireland','EU'),
    (108,44,'IM','IMN','Isle of Man','EU'),
    (109,972,'IL','ISR','Israel','AS'),
    (110,39,'IT','ITA','Italy','EU'),
    (111,1876,'JM','JAM','Jamaica','NA'),
    (112,81,'JP','JPN','Japan','AS'),
    (113,44,'JE','JEY','Jersey','EU'),
    (114,962,'JO','JOR','Jordan','AS'),
    (115,7,'KZ','KAZ','Kazakhstan','AS'),
    (116,254,'KE','KEN','Kenya','AF'),
    (117,686,'KI','KIR','Kiribati','OC'),
    (118,850,'KP','PRK','Korea, Democratic Peoples Republic of','AS'),
    (119,82,'KR','KOR','Korea, Republic of','AS'),
    (120,381,'XK','XKX','Kosovo','EU'),
    (121,965,'KW','KWT','Kuwait','AS'),
    (122,996,'KG','KGZ','Kyrgyzstan','AS'),
    (123,856,'LA','LAO','Lao Peoples Democratic Republic','AS'),
    (124,371,'LV','LVA','Latvia','EU'),
    (125,961,'LB','LBN','Lebanon','AS'),
    (126,266,'LS','LSO','Lesotho','AF'),
    (127,231,'LR','LBR','Liberia','AF'),
    (128,218,'LY','LBY','Libyan Arab Jamahiriya','AF'),
    (129,423,'LI','LIE','Liechtenstein','EU'),
    (130,370,'LT','LTU','Lithuania','EU'),
    (131,352,'LU','LUX','Luxembourg','EU'),
    (132,853,'MO','MAC','Macao','AS'),
    (133,389,'MK','MKD','Macedonia, the Former Yugoslav Republic of','EU'),
    (134,261,'MG','MDG','Madagascar','AF'),
    (135,265,'MW','MWI','Malawi','AF'),
    (136,60,'MY','MYS','Malaysia','AS'),
    (137,960,'MV','MDV','Maldives','AS'),
    (138,223,'ML','MLI','Mali','AF'),
    (139,356,'MT','MLT','Malta','EU'),
    (140,692,'MH','MHL','Marshall Islands','OC'),
    (141,596,'MQ','MTQ','Martinique','NA'),
    (142,222,'MR','MRT','Mauritania','AF'),
    (143,230,'MU','MUS','Mauritius','AF'),
    (144,269,'YT','MYT','Mayotte','AF'),
    (145,52,'MX','MEX','Mexico','NA'),
    (146,691,'FM','FSM','Micronesia, Federated States of','OC'),
    (147,373,'MD','MDA','Moldova, Republic of','EU'),
    (148,377,'MC','MCO','Monaco','EU'),
    (149,976,'MN','MNG','Mongolia','AS'),
    (150,382,'ME','MNE','Montenegro','EU'),
    (151,1664,'MS','MSR','Montserrat','NA'),
    (152,212,'MA','MAR','Morocco','AF'),
    (153,258,'MZ','MOZ','Mozambique','AF'),
    (154,95,'MM','MMR','Myanmar','AS'),
    (155,264,'NA','NAM','Namibia','AF'),
    (156,674,'NR','NRU','Nauru','OC'),
    (157,977,'NP','NPL','Nepal','AS'),
    (158,31,'NL','NLD','Netherlands','EU'),
    (159,599,'AN','ANT','Netherlands Antilles','NA'),
    (160,687,'NC','NCL','New Caledonia','OC'),
    (161,64,'NZ','NZL','New Zealand','OC'),
    (162,505,'NI','NIC','Nicaragua','NA'),
    (163,227,'NE','NER','Niger','AF'),
    (164,234,'NG','NGA','Nigeria','AF'),
    (165,683,'NU','NIU','Niue','OC'),
    (166,672,'NF','NFK','Norfolk Island','OC'),
    (167,1670,'MP','MNP','Northern Mariana Islands','OC'),
    (168,47,'NO','NOR','Norway','EU'),
    (169,968,'OM','OMN','Oman','AS'),
    (170,92,'PK','PAK','Pakistan','AS'),
    (171,680,'PW','PLW','Palau','OC'),
    (172,970,'PS','PSE','Palestinian Territory, Occupied','AS'),
    (173,507,'PA','PAN','Panama','NA'),
    (174,675,'PG','PNG','Papua New Guinea','OC'),
    (175,595,'PY','PRY','Paraguay','SA'),
    (176,51,'PE','PER','Peru','SA'),
    (177,63,'PH','PHL','Philippines','AS'),
    (178,64,'PN','PCN','Pitcairn','OC'),
    (179,48,'PL','POL','Poland','EU'),
    (180,351,'PT','PRT','Portugal','EU'),
    (181,1787,'PR','PRI','Puerto Rico','NA'),
    (182,974,'QA','QAT','Qatar','AS'),
    (183,262,'RE','REU','Reunion','AF'),
    (184,40,'RO','ROM','Romania','EU'),
    (185,70,'RU','RUS','Russian Federation','AS'),
    (186,250,'RW','RWA','Rwanda','AF'),
    (187,590,'BL','BLM','Saint Barthelemy','NA'),
    (188,290,'SH','SHN','Saint Helena','AF'),
    (189,1869,'KN','KNA','Saint Kitts and Nevis','NA'),
    (190,1758,'LC','LCA','Saint Lucia','NA'),
    (191,590,'MF','MAF','Saint Martin','NA'),
    (192,508,'PM','SPM','Saint Pierre and Miquelon','NA'),
    (193,1784,'VC','VCT','Saint Vincent and the Grenadines','NA'),
    (194,684,'WS','WSM','Samoa','OC'),
    (195,378,'SM','SMR','San Marino','EU'),
    (196,239,'ST','STP','Sao Tome and Principe','AF'),
    (197,966,'SA','SAU','Saudi Arabia','AS'),
    (198,221,'SN','SEN','Senegal','AF'),
    (199,381,'RS','SRB','Serbia','EU'),
    (200,381,'CS','SCG','Serbia and Montenegro','EU'),
    (201,248,'SC','SYC','Seychelles','AF'),
    (202,232,'SL','SLE','Sierra Leone','AF'),
    (203,65,'SG','SGP','Singapore','AS'),
    (204,1,'SX','SXM','Sint Maarten','NA'),
    (205,421,'SK','SVK','Slovakia','EU'),
    (206,386,'SI','SVN','Slovenia','EU'),
    (207,677,'SB','SLB','Solomon Islands','OC'),
    (208,252,'SO','SOM','Somalia','AF'),
    (209,27,'ZA','ZAF','South Africa','AF'),
    (210,500,'GS','SGS','South Georgia and the South Sandwich Islands','AN'),
    (211,211,'SS','SSD','South Sudan','AF'),
    (212,34,'ES','ESP','Spain','EU'),
    (213,94,'LK','LKA','Sri Lanka','AS'),
    (214,249,'SD','SDN','Sudan','AF'),
    (215,597,'SR','SUR','Suriname','SA'),
    (216,47,'SJ','SJM','Svalbard and Jan Mayen','EU'),
    (217,268,'SZ','SWZ','Swaziland','AF'),
    (218,46,'SE','SWE','Sweden','EU'),
    (219,41,'CH','CHE','Switzerland','EU'),
    (220,963,'SY','SYR','Syrian Arab Republic','AS'),
    (221,886,'TW','TWN','Taiwan, Province of China','AS'),
    (222,992,'TJ','TJK','Tajikistan','AS'),
    (223,255,'TZ','TZA','Tanzania, United Republic of','AF'),
    (224,66,'TH','THA','Thailand','AS'),
    (225,670,'TL','TLS','Timor-Leste','AS'),
    (226,228,'TG','TGO','Togo','AF'),
    (227,690,'TK','TKL','Tokelau','OC'),
    (228,676,'TO','TON','Tonga','OC'),
    (229,1868,'TT','TTO','Trinidad and Tobago','NA'),
    (230,216,'TN','TUN','Tunisia','AF'),
    (231,90,'TR','TUR','Turkey','AS'),
    (232,7370,'TM','TKM','Turkmenistan','AS'),
    (233,1649,'TC','TCA','Turks and Caicos Islands','NA'),
    (234,688,'TV','TUV','Tuvalu','OC'),
    (235,256,'UG','UGA','Uganda','AF'),
    (236,380,'UA','UKR','Ukraine','EU'),
    (237,971,'AE','ARE','United Arab Emirates','AS'),
    (238,44,'GB','GBR','United Kingdom','EU'),
    (239,1,'US','USA','United States','NA'),
    (240,1,'UM','UMI','United States Minor Outlying Islands','NA'),
    (241,598,'UY','URY','Uruguay','SA'),
    (242,998,'UZ','UZB','Uzbekistan','AS'),
    (243,678,'VU','VUT','Vanuatu','OC'),
    (244,58,'VE','VEN','Venezuela','SA'),
    (245,84,'VN','VNM','Viet Nam','AS'),
    (246,1284,'VG','VGB','Virgin Islands, British','NA'),
    (247,1340,'VI','VIR','Virgin Islands, U.s.','NA'),
    (248,681,'WF','WLF','Wallis and Futuna','OC'),
    (249,212,'EH','ESH','Western Sahara','AF'),
    (250,967,'YE','YEM','Yemen','AS'),
    (251,260,'ZM','ZMB','Zambia','AF'),
    (252,263,'ZW','ZWE','Zimbabwe','AF');

CREATE TABLE IF NOT EXISTS `continents` (
	`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`continent_code` varchar(2) DEFAULT NULL,
	`continent_name` varchar(30) DEFAULT NULL,
	PRIMARY KEY (`id`)
);

INSERT INTO `continents` (`id`, `continent_code`, `continent_name`) VALUES
    (1, 'AF', 'Africa'),
    (2, 'AN', 'Antarctica'),
    (3, 'AS', 'Asia'),
    (4, 'EU', 'Europe'),
    (5, 'OC', 'Australia'),
    (6, 'NA', 'North America'),
    (7, 'SA', 'South America');

CREATE TABLE IF NOT EXISTS `users`(
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `full_name` varchar(70) NOT NULL,
    `email` varchar(255) NOT NULL,
    `password` varchar(255) NOT NULL,
    `interest_id` int(10) UNSIGNED NOT NULL,
    `institution` varchar(70) NOT NULL,
    `country_code` char(2) NOT NULL,
    `grant_contact_info_permission` boolean NOT NULL,
    `grant_uib_permission` boolean NOT NULL,
    `email_confirmed` boolean DEFAULT 0,
    `active` boolean DEFAULT 1,
    PRIMARY KEY (`id`),
    FOREIGN KEY(`interest_id`) REFERENCES `interests`(`id`),
    FOREIGN KEY(`country_code`) REFERENCES `countries`(`country_code`)
);

CREATE TABLE `roles`(
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` varchar(30) NOT NULL,
    `code` varchar(3) NOT NULL,
    PRIMARY KEY (`id`)
);

INSERT INTO `roles`(`name`, `code`) VALUES ('Administrator', 'ADM'), ('User', 'USR');


CREATE TABLE IF NOT EXISTS `user_roles`(
    `user_id` int(10) UNSIGNED NOT NULL,
    `role_id` int(10) UNSIGNED NOT NULL,
    FOREIGN KEY(`user_id`) REFERENCES `users`(`id`),
    FOREIGN KEY(`role_id`) REFERENCES `roles`(`id`)
);

CREATE TABLE IF NOT EXISTS `email_confirmations`(
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` int(10) UNSIGNED NOT NULL,
    `confirmation_code` varchar(36) NOT NULL,
    `issued_at` datetime NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY(`user_id`) REFERENCES `users`(`id`)
);

CREATE TABLE IF NOT EXISTS `statuses`(
	`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` varchar(30) NOT NULL,
    `code` varchar(4) NOT NULL,
    PRIMARY KEY (`id`)
);

INSERT INTO `statuses`(`name`, `code`) VALUES ('Pending', 'PEND'), ('Approved', 'APPR'), ('Discarded', 'DISC');

CREATE TABLE IF NOT EXISTS `images`(
	`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` int(10) UNSIGNED NOT NULL,
    `location` varchar(255) NOT NULL,
    `date` datetime NOT NULL,
    `filename` varchar(41) NOT NULL,
    `status_id` int(10) unsigned NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY(`user_id`) REFERENCES `users`(`id`),
    FOREIGN KEY(`status_id`) REFERENCES `statuses`(`id`)
);

CREATE TABLE IF NOT EXISTS `password_recoveries`(
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` int(10) UNSIGNED NOT NULL,
    `confirmation_code` varchar(36) NOT NULL,
    `issued_at` datetime NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY(`user_id`) REFERENCES `users`(`id`)
);
