name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./consumer-model/Dockerfile
            image-name: jellytporing-model
          - dockerfile: ./prometheus/Dockerfile
            image-name: jellytoring-prometheus
          - dockerfile: ./grafana/Dockerfile
            image-name: jellytoring-grafana
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ${{ matrix.dockerfile }}
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image-name }}:latest
        cache: enabled
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image-name }}:buildcache  
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image-name }}:buildcache,mode=max
